import { join, dirname, basename } from 'node:path';
import {
  AggregatedAnalysis,
  CONTEXT_FILE_NAME,
  MEMORY_FILE_NAME,
  ValidationError,
} from '@devbrain/shared';
import { FilesystemService } from '../filesystem/filesystem.service.js';

export class ContextService {
  constructor(private readonly fsService: FilesystemService = new FilesystemService()) {}

  /**
   * Generates and writes context.md to the target directory.
   */
  async generateContext(analysis: AggregatedAnalysis, memoryDir: string): Promise<string> {
    const targetDir = basename(memoryDir) === 'memory' ? dirname(memoryDir) : memoryDir;
    const contextPath = join(targetDir, CONTEXT_FILE_NAME);

    const contextContent = this.buildContextString(analysis);

    const fileContent = [
      '<!-- ⚠️ THIS FILE IS AUTO-GENERATED BY DEVBRAIN. -->',
      '<!-- DO NOT EDIT. YOUR CHANGES WILL BE OVERWRITTEN. -->',
      '',
      contextContent,
    ].join('\n');

    await this.fsService.writeAtomic(contextPath, fileContent);
    return contextContent;
  }

  /**
   * Reads project memory and compiles it into a single token-efficient string.
   */
  async buildContext(memoryDir: string): Promise<string> {
    const targetDir = basename(memoryDir) === 'memory' ? dirname(memoryDir) : memoryDir;
    const jsonPath = join(targetDir, MEMORY_FILE_NAME);

    // If memory.json exists, build context from it
    if (await this.fsService.exists(jsonPath)) {
      try {
        const analysis = await this.fsService.readJson<AggregatedAnalysis>(jsonPath);
        return this.buildContextString(analysis);
      } catch {
        // Fall back to folder scanning if parsing fails
      }
    }

    // Ensure memory folder exists if memory.json is not present (backward compatibility check)
    if (!(await this.fsService.exists(memoryDir))) {
      throw new ValidationError(
        'Project memory directory not found.',
        `The directory ${memoryDir} does not exist.`,
        'Run "devbrain learn" to scan the repository and populate the memory files first.',
      );
    }

    // Fallback: Read individual .md files (v0.1 structure)
    const files = [
      'summary.md',
      'stack.md',
      'architecture.md',
      'features.md',
      'rules.md',
      'timeline.md',
    ];
    const parts: string[] = [];

    parts.push('<!-- START OF DEVBRAIN AI ASSISTANT CONTEXT SCHEMA -->');
    parts.push('# DEVBRAIN PROJECT CONTEXT INDEX');
    parts.push('');

    for (const file of files) {
      const filePath = join(memoryDir, file);
      if (!(await this.fsService.exists(filePath))) {
        continue;
      }

      const content = await this.fsService.read(filePath);
      const formatted = this.normalizeHeadings(file, content);
      parts.push(formatted);
      parts.push('');
    }

    parts.push('<!-- END OF DEVBRAIN AI ASSISTANT CONTEXT SCHEMA -->');
    return parts.join('\n');
  }

  private buildContextString(analysis: AggregatedAnalysis): string {
    const readmeData = analysis.analyzers.readme || {};
    const packageJsonData = analysis.analyzers['package-json'] || {};
    const tsconfigData = analysis.analyzers.tsconfig || {};
    const gitData = analysis.analyzers.git || {};
    const sourceCodeData = analysis.analyzers['source-code'] || {};

    const projectName = analysis.projectName || packageJsonData.name || 'unnamed-project';
    const overview = readmeData.description || 'No description available.';

    const filesCount = analysis.files.length;
    const keyFiles = analysis.files.filter((f) => 
      f.includes('package.json') ||
      f.includes('tsconfig.json') ||
      f.includes('routes') ||
      f.includes('controller') ||
      f.includes('service') ||
      f.includes('model') ||
      f.includes('entity')
    ).slice(0, 30);

    const modules = (sourceCodeData.modules || [])
      .map((m: any) => `- Module: \`${m.name}\` (Type: ${m.type}, File: \`${m.filePath}\`)\n  Classes: [${m.classes.join(', ')}]\n  Functions: [${m.functions.join(', ')}]`)
      .join('\n');

    const apis = (sourceCodeData.apis || [])
      .map((a: any) => `- ${a.method} ${a.path}`)
      .join('\n');

    const dbs = (sourceCodeData.databaseEntities || []).map((d: string) => `- Model: ${d}`).join('\n');
    const auths = (sourceCodeData.authMethods || []).map((a: string) => `- Auth: ${a}`).join('\n');
    const externals = (sourceCodeData.externalServices || []).map((e: string) => `- Service: ${e}`).join('\n');

    const commits = (gitData.recentCommits || [])
      .slice(0, 3)
      .map((c: any) => `- [${c.hash}] ${c.message}`)
      .join('\n');

    return [
      '# DEVBRAIN AI CONTEXT',
      '',
      `## Project: ${projectName}`,
      overview,
      '',
      `## Tech Stack & Language`,
      `- Core Languages: ${analysis.technologies.join(', ') || 'None detected'}`,
      `- Frameworks: ${analysis.frameworks.join(', ') || 'None detected'}`,
      `- TS Compiler Target: ${tsconfigData.target || 'N/A'}`,
      `- Strict Mode: ${tsconfigData.strict ? 'Enabled' : 'Disabled'}`,
      '',
      '## Project Architecture & Modules',
      modules || '- No specific source code modules identified.',
      '',
      '## API Endpoints',
      apis || '- No routes detected.',
      '',
      '## Database & Schemas',
      dbs || '- No database models identified.',
      '',
      '## Authentication Systems',
      auths || '- Default token/credentials handling.',
      '',
      '## Third-Party Integrations',
      externals || '- No external API integrations.',
      '',
      `## Repository Structure (${filesCount} total files)`,
      'Important files:',
      keyFiles.map((kf) => `- \`${kf}\``).join('\n') || '- No critical files highlighted.',
      '',
      '## Recent Changes',
      commits || '- No git commit log available.',
      '',
    ].join('\n');
  }

  private normalizeHeadings(fileName: string, content: string): string {
    const sectionName = fileName.replace('.md', '').toUpperCase();
    const lines = content.split('\n');
    const processedLines: string[] = [`## SECTION: ${sectionName}`, ''];

    for (let line of lines) {
      line = line.trimEnd();
      if (line.startsWith('# ')) {
        processedLines.push(`### ${line.substring(2)}`);
      } else if (line.startsWith('## ')) {
        processedLines.push(`#### ${line.substring(3)}`);
      } else if (line.startsWith('### ')) {
        processedLines.push(`##### ${line.substring(4)}`);
      } else {
        processedLines.push(line);
      }
    }

    return processedLines.join('\n').trim();
  }
}
